# Generated by Django 5.2.8 on 2026-06-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0006_album_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.JSONField(blank=True, default=list, verbose_name='لیست ترک\u200cها'),
        ),
    ]
