# Generated by Django 5.2.8 on 2026-06-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0009_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='average_rating',
            field=models.FloatField(default=0, verbose_name='میانگین امتیاز'),
        ),
    ]
