# Generated by Django 5.2.8 on 2026-07-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0010_album_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='پیش\u200cپخش صوتی'),
        ),
    ]
