# Generated by Django 5.2.8 on 2026-07-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0011_album_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='عکس کاور'),
        ),
    ]
