# Generated by Django 5.2.8 on 2026-07-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinyl', '0012_album_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('NN', 'No definido'), ('Rock', 'Rock'), ('Indie Rock', 'Indie Rock'), ('Indie Pop', 'Indie Pop'), ('Alternative Rock', 'Alternative Rock'), ('Metal', 'Metal'), ('Punk', 'Punk'), ('Pop', 'Pop'), ('K-pop', 'K-pop'), ('J-pop', 'J-pop'), ('Jazz', 'Jazz'), ('Blues', 'Blues'), ('Disco', 'Disco'), ('Salsa', 'Salsa'), ('Bachata', 'Bachata'), ('Reggaeton', 'Reggaeton'), ('Cumbia', 'Cumbia'), ('Dembow', 'Dembow'), ('Bolero', 'Bolero'), ('Electronic', 'Electronic'), ('Techno', 'Techno'), ('Hip Hop', 'Hip Hop'), ('Reggae', 'Reggae'), ('Trap', 'Trap')], default='NN', max_length=100),
        ),
    ]
